### ISSUE TITLE
Module not working

### ISSUE THREAD

**Issue by cassiocsantana** [nuxt-modules/eslint#98]
[13:23:42]  WARN  warning: LintOnStart is turned on, and it will check for all matching files.
  Plugin: vite-plugin-eslint

[13:23:42] 
[13:23:42]  ERROR  Cannot restart nuxt:  No ESLint configuration found in /home/project/my/project

  at formatError (node_modules/vite/dist/node/chunks/dep-e8f070e8.js:42645:46)
  at Context.error (node_modules/vite/dist/node/chunks/dep-e8f070e8.js:42641:19)
  at Context.buildStart (node_modules/vite-plugin-eslint/dist/index.mjs:1:1766)
  at runMicrotasks (<anonymous>)
  at processTicksAndRejections (internal/process/task_queues.js:95:5)
  at async Promise.all (index 7)
  at async hookParallel (node_modules/vite/dist/node/chunks/dep-e8f070e8.js:42512:9)
  at async Object.buildStart (node_modules/vite/dist/node/chunks/dep-e8f070e8.js:42824:13)
  at async node_modules/vite/dist/node/chunks/dep-e8f070e8.js:63536:13
  at async _createServer (node_modules/vite/dist/node/chunks/dep-e8f070e8.js:63566:9)
  at async buildClient (node_modules/@nuxt/vite-builder/dist/shared/vite-builder.3fe5d19a.mjs:545:24)
  at async bundle (node_modules/@nuxt/vite-builder/dist/shared/vite-builder.3fe5d19a.mjs:1194:3)
  at async build (node_modules/nuxt/dist/index.mjs:3414:5)
  at async Promise.all (index 1)
  at async load (node_modules/nuxi/dist/chunks/dev.mjs:219:9)
  at async _applyPromised (node_modules/nuxi/dist/chunks/dev.mjs:96:10)

**Comment by tberk** [comment]
Do you have a .eslintrc.cjs file in root for config?

**Comment by cassiocsantana** [comment]
yes, because there was a need to add the prettier. for some reason it is giving this error.
